FROM ubuntu:22.04

RUN apt update
RUN apt install -y build-essential cmake git googletest googletest-tools lcov libgmock-dev libgtest-dev python3-all

RUN mkdir /src
RUN git clone https://github.com/marek-cel/libmcutils.git /src
RUN cd /src; cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_TESTING=Off -B build
RUN cd /src; cmake --build build --config Release -j 4
RUN cd /src; cmake --build build --config Release --target install
RUN rm -r /src
